export const electronicCarArr = [
  {
    name: "아이오닉 9",
    price: "6,715",
    fuelEfficiency: "~4.3 km/kwhh",
    personnel: "6/7",
    displacement: "-",
    smallimg: "ionic9_small",
    bigimg: "ionic9_big",
    detailtitle: "살아보세요",
  },
  {
    name: "ST1",
    price: "5,555",
    fuelEfficiency: "~4.3 km/kwhh",
    personnel: "2",
    displacement: "-",
    smallimg: "ST1_small",
    bigimg: "ST1_big",
    detailtitle: "내일을 꿈꾸는 모빌리티",
  },
  {
    name: "넥소",
    price: "6,950",
    fuelEfficiency: "~96.2 km/kg",
    personnel: "5",
    displacement: "-",
    smallimg: "nexo_small",
    bigimg: "nexo_big",
    detailtitle: "Positive Energy, NEXO",
  },
  {
    name: "아이오닉 6",
    price: "4,695",
    fuelEfficiency: "~6.2 km/kwhh",
    personnel: "5",
    displacement: "-",
    smallimg: "ionic6_small",
    bigimg: "ionic6_big",
    detailtitle: "내가 만드는 세상",
  },
  {
    name: "코나 Electronic",
    price: "4,142",
    fuelEfficiency: "~5.5 km/kwhh",
    personnel: "5",
    displacement: "-",
    smallimg: "코나_small",
    bigimg: "코나_big",
    detailtitle: "새로운 차원을 라이프",
  },
  {
    name: "더 뉴 아이오닉5",
    price: "4,700",
    fuelEfficiency: "~5.2 km/kwhh",
    personnel: "5",
    displacement: "-",
    smallimg: "ionic5_small",
    bigimg: "ionic5_big",
    detailtitle: "내가 선택한 단 하나의 전기차",
  },
  {
    name: "포터 Ⅱ Electronic",
    price: "4,395",
    fuelEfficiency: "~3.1 km/kwhh",
    personnel: "3",
    displacement: "-",
    smallimg: "포터2_small",
    bigimg: "포터2_big",
    detailtitle: "새로운 친환경 EV 트럭",
  },
  {
    name: "포터 Ⅱ Electronic 특장차",
    price: "4,800",
    fuelEfficiency: "-",
    personnel: "3",
    displacement: "-",
    smallimg: "포터2전기_small",
    bigimg: "포터2전기_big",
    detailtitle: "내일을 꿈꾸는 모빌리티",
  },
];

export const NcarArr = [
  {
    name: "아이오닉 5 N",
    price: "7,700",
    fuelEfficiency: "~3.7 km/kWh",
    personnel: "5",
    displacement: "-",
    smallimg: "ionic5n_small",
    bigimg: "ionic5n_big",
    detailtitle: "Everyday N Life",
  },
  {
    name: "아반떼 N",
    price: "3,309",
    fuelEfficiency: "~10km/L",
    personnel: "5",
    displacement: "~1998 cc",
    smallimg: "아반떼n_small",
    bigimg: "아반떼n_big",
    detailtitle: "Never just drive",
  },
];

export const passengerCarArr = [
  {
    name: "쏘나타 디 엣지",
    price: "2,788",
    fuelEfficiency: "~13km/L",
    personnel: "5",
    displacement: "~1999 cc",
    smallimg: "쏘나타디엣지_small",
    bigimg: "쏘나타디엣지_big",
    detailtitle: "Keep Growing",
  },
  {
    name: "쏘나타 디 엣지 Hybrid",
    price: "3,232",
    fuelEfficiency: "~19km/L",
    personnel: "5",
    displacement: "~1998 cc",
    smallimg: "쏘나타디엣지하이브리드_small",
    bigimg: "쏘나타디엣지하이브리드_big",
    detailtitle: "Never just drive",
  },
  {
    name: "아반떼",
    price: "1,964",
    fuelEfficiency: "~15km/L",
    personnel: "5",
    displacement: "~1598 cc",
    smallimg: "아반떼_small",
    bigimg: "아반떼_big",
    detailtitle: "지금, 더 매력적인 AVANTE",
  },
  {
    name: "아반떼 Hybrid",
    price: "2,485",
    fuelEfficiency: "~21.1km/L",
    personnel: "5",
    displacement: "~1580 cc",
    smallimg: "아반떼하이브리드_small",
    bigimg: "아반떼하이브리드_big",
    detailtitle: "지금, 더 매력적인 AVANTE",
  },
  {
    name: "그랜저",
    price: "3,711",
    fuelEfficiency: "~11.7km/L",
    personnel: "5",
    displacement: "~3470 cc",
    smallimg: "그랜저_small",
    bigimg: "그랜저_big",
    detailtitle: "Outclass GRANDEUR",
  },
  {
    name: "그랜저 Hybrid",
    price: "4,267",
    fuelEfficiency: "~18km/L",
    personnel: "5",
    displacement: "~1598 cc",
    smallimg: "그랜저하이브리드_small",
    bigimg: "그랜저하이브리드_big",
    detailtitle: "Outclass GRANDEUR",
  },
];

export const suvArr = [
  {
    name: "디 올 뉴 팰리세이드",
    price: "4,383",
    fuelEfficiency: "~9.7km/L",
    personnel: "7/9",
    displacement: "~2,497 cc",
    smallimg: "디올뉴팰리세이드_small",
    bigimg: "디올뉴팰리세이드_big",
    detailtitle: "세상을 품는 힘",
  },
  {
    name: "디 올 뉴 팰리세이드 Hybrid",
    price: "4,982",
    fuelEfficiency: "-",
    personnel: "7/9",
    displacement: "~2,497 cc",
    smallimg: "디올뉴팰리세이드하이브리드_small",
    bigimg: "디올뉴팰리세이드하이브리드_big",
    detailtitle: "Keep Growing",
  },
  {
    name: "투싼",
    price: "2,729",
    fuelEfficiency: "~14.3km/L",
    personnel: "5",
    displacement: "~1,998 cc",
    smallimg: "투싼_small",
    bigimg: "투싼_big",
    detailtitle: "날개를 달다",
  },
  {
    name: "투싼 Hybrid",
    price: "3,205",
    fuelEfficiency: "~16.2km/L",
    personnel: "5",
    displacement: "~1598 cc",
    smallimg: "투싼하이브리드_small",
    bigimg: "투싼하이브리드_big",
    detailtitle: "날개를 달다",
  },
  {
    name: "베뉴",
    price: "2,113",
    fuelEfficiency: "~13.7km/L",
    personnel: "5",
    displacement: "~1,598 cc",
    smallimg: "베뉴_small",
    bigimg: "베뉴_big",
    detailtitle: "혼라이프를 즐기다",
  },
  {
    name: "코나",
    price: "2,409",
    fuelEfficiency: "~13.6km/L",
    personnel: "5",
    displacement: "~1,999 cc",
    smallimg: "코나_small",
    bigimg: "코나_big",
    detailtitle: "새로운 차원을 플레이",
  },
  {
    name: "코나 Hybrid",
    price: "2,955",
    fuelEfficiency: "~19.8km/L",
    personnel: "5",
    displacement: "~1,589 cc",
    smallimg: "코나하이브리드_small",
    bigimg: "코나하이브리드_big",
    detailtitle: "새로운 차원을 플레이",
  },
  {
    name: "싼타페",
    price: "3,492",
    fuelEfficiency: "~11km/L",
    personnel: "5/6/7",
    displacement: "~2,497 cc",
    smallimg: "산타페_small",
    bigimg: "산타페_big",
    detailtitle: "패밀리 SUV의 진화",
  },
  {
    name: "싼타페 Hybrid",
    price: "3,870",
    fuelEfficiency: "~15.5km/L",
    personnel: "5/6/7",
    displacement: "~1,598 cc",
    smallimg: "산타페하이브리드_small",
    bigimg: "산타페하이브리드_big",
    detailtitle: "일상과 일상 사이를 열다.",
  },
  {
    name: "더 뉴 캐스퍼",
    price: "2,788",
    fuelEfficiency: "~13km/L",
    personnel: "5",
    displacement: "~1999 cc",
    smallimg: "쏘나타디엣지_small",
    bigimg: "쏘나타디엣지_big",
    detailtitle: "Keep Growing",
  },
];

export const linkUrlList = [
  { id: "header_img", url: "https://www.hyundai.com/kr/ko/e/" },
  { id: "model", url: "https://www.hyundai.com/kr/ko/e/all-vehicles" },
  {
    id: "shop",
    url: "https://shop.hyundai.com/section/welcome?utm_source=hyundai_d_com&utm_medium=affiliates&utm_campaign=gnb",
  },
  { id: "genesis", url: "https://www.genesis.com/kr/ko/main.html" },
  { id: "casper", url: "https://casper.hyundai.com/" },
  {
    id: "trendyHyundai",
    url: "https://www.hyundai.com/kr/ko/e/service-membership/ev/hi-ev",
  },
  {
    id: "en",
    url: "https://www.hyundai.com/kr/en/catalog_price/hydrogen_ev",
  },
  {
    id: "cn",
    url: "https://www.hyundai.com/kr/en/catalog_price/hydrogen_ev",
  },
  {
    id: "worldWide",
    url: "https://www.hyundai.com/worldwide/ko#utm_source=hmc-kr&utm_medium=referral&utm_campaign=top_util",
  },
  {
    id: "global",
    url: "https://trucknbus.hyundai.com/global/en/",
  },
  {
    id: "perLogin",
    url: "https://idpconnect-kr.hyundai.com/auth/api/v2/user/oauth2/authorize?client_id=2b6b3d2d-5ccc-497f-8e8b-e9b2d7582097&redirect_uri=https%3A%2F%2Fwww.hyundai.com%2Fkr%2Fko%2Fccspcallback.html%3Fhmgid%3D2&response_type=code&scope=&state=login&connector_client_id=hmgid1.0-2b6b3d2d-5ccc-497f-8e8b-e9b2d7582097&ui_locales=&connector_scope=&connector_session_key=dca02db6-f693-48b9-bd02-a26c1988cd1d",
  },
  {
    id: "corLogin",
    url: "https://www.hyundai.com/kr/ko/corporation-login",
  },
];

export const moveList = [
  {
    clickId: document.querySelector("#electric"),
    moveId: document.querySelector("#electronicCarList1"),
  },
  {
    clickId: document.querySelector("#n"),
    moveId: document.querySelector("#Ncar"),
  },
  {
    clickId: document.querySelector("#passenger"),
    moveId: document.querySelector("#passengerCar"),
  },
  {
    clickId: document.querySelector("#suv"),
    moveId: document.querySelector("#SUV"),
  },
];
